# Site settings
title: Coding Lane
SEOTitle: 技术总结与思考 | Coding Lane
timezone: Asia/Shanghai
header-img: img/bit (3).jpg
email: xie96808@gmail.com
description: "Rest at the end, not in the middle"
keyword: "NONE"
url: "http://xie96808.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "记录工作中遇到的技术难点和黑科技。如果有帮到你的话，我会非常开心: )"
sidebar-avatar: /img/touxiang2.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     NONE
zhihu_username:     xie-yu-wei-35
github_username:    xie96808
#facebook_username:  NONE
#jianshu_username:   NONE
twitter_username:  BillyXie5
instagram_username:  billy_whynot



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 12
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 4dede977f9d18025b3b5                            #生成的clientID
  clientSecret: e581aa2d1471ebbb0785b39b54d748cff07a1301    #生成的clientSecret
  repo: xie96808.github.io    #仓库名称
  owner: xie96808    #github用户名
  admin: xie96808
  distractionFreeMode: true #是否启用类似FB的阴影遮罩




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

